#!/usr/bin/env python3
"""
apply_signing.py — inject the release signing config into the generated Gradle file.

`android/` is generated by bootstrap.sh (`flutter create`), so it is NOT tracked
in git and any hand-edit to android/app/build.gradle.kts is lost the next time
it regenerates — including in CI, which bootstraps from scratch. This script
re-applies the signing wiring idempotently.

Behaviour: release builds are signed with the upload key when
android/key.properties exists, and fall back to the debug key when it doesn't,
so a fresh clone (and a secret-less CI run) still produces an installable APK.

Usage:  python3 tools/apply_signing.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GRADLE = os.path.join(HERE, "..", "android", "app", "build.gradle.kts")

IMPORTS = """import java.util.Properties
import java.io.FileInputStream

"""

LOADER = """
// Upload-key credentials. android/key.properties is git-ignored; when absent
// (fresh clone, CI without secrets) we fall back to the debug key below.
val keystoreProperties = Properties()
val keystorePropertiesFile = rootProject.file("key.properties")
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}
"""

SIGNING = """    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties["keyAlias"] as String?
            keyPassword = keystoreProperties["keyPassword"] as String?
            storeFile = (keystoreProperties["storeFile"] as String?)?.let { file(it) }
            storePassword = keystoreProperties["storePassword"] as String?
        }
    }

    buildTypes {
        release {
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
"""

# The closing brace must be anchored to buildTypes' own indentation, otherwise
# the non-greedy match stops at the nested `release { ... }` and leaves a stray
# brace behind.
BUILDTYPES_RE = re.compile(
    r"(?P<indent>[ \t]*)buildTypes\s*\{.*?\n(?P=indent)\}\n", re.DOTALL)


def main():
    path = os.path.normpath(GRADLE)
    if not os.path.exists(path):
        sys.exit(f"{path} not found — run bootstrap.sh first.")

    src = open(path, encoding="utf-8").read()

    if "signingConfigs" in src:
        print("✓ signing config already present — nothing to do")
        return

    if not src.startswith("import "):
        src = IMPORTS + src

    # Insert the loader just before the android { } block.
    src = src.replace("\nandroid {", LOADER + "\nandroid {", 1)

    # Replace the template's buildTypes block with signingConfigs + buildTypes.
    src, n = BUILDTYPES_RE.subn(SIGNING, src, count=1)
    if n == 0:
        sys.exit("could not find a buildTypes block to replace — inspect the file.")

    open(path, "w", encoding="utf-8").write(src)
    print(f"✓ signing config injected into {path}")


if __name__ == "__main__":
    main()
